remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: âœ¨ï¸ L&emsp;U&emsp;N&emsp;A ğŸŒ™
logo: Ui.png
description: Your nature-themed graphical user interface (GUI) desktop app that helps you complete your tasks in the prettiest way possible ğŸŒ»
