remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: <h1 align = "center">âœ¨ï¸ L&emsp;U&emsp;N&emsp;A ğŸŒ™</h1>
logo: assets/luna.png
description: <p align = "center">Complete your tasks by night.<p align = "center">
background-color: #FFF8F4
